# MySQL.  Versions 5.0+ are recommended.
default: &default
  adapter: mysql2
  encoding: utf8mb4
  collation: utf8mb4_unicode_ci
  pool: 5
  username: root
  password:

development:
  <<: *default
  database: stronger_dev

test:
  <<: *default
  database: stronger_test

production:
  <<: *default
  database: db_stronger
  username: root
  password:
